const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const ts=require('typescript'),React=require('react'),{create,act}=require('react-test-renderer');
const {prefs,catalog}=require('./basket-fixtures.cjs');
const {generateBasket}=require('../services/basket/basketGenerator.ts');
const {newSavedBasket}=require('../services/basket/persistence.ts');
global.IS_REACT_ACT_ENVIRONMENT=true;
let params={},generated=0,saveCalls=0,resolveSave,load=async()=>catalog;
const saved=newSavedBasket(generateBasket(prefs(),catalog),prefs(),prefs().userId);
const preferenceState={ready:true,saved:prefs()};
const components=Object.fromEntries(['EmptyState','PrimaryButton','Screen','ScreenHeader','SecondaryButton'].map(name=>[name,props=>React.createElement(name,props,props.children)]));
const originalLoad=Module._load;
Module._load=function(request,parent,isMain){
  if(request==='@react-native-async-storage/async-storage')return {__esModule:true,default:{getItem:async()=>null,setItem:async()=>{}}};
  if(request==='react-native')return {ActivityIndicator:'Spinner',Text:'Text'};
  if(request==='expo-router')return {router:{dismissTo:()=>{}},useLocalSearchParams:()=>params};
  if(request==='@/components/ui')return components;
  if(request==='@/components/MealPlanReview')return {MealPlanReview:props=>React.createElement('MealReview',props)};
  if(request==='@/services/meals/planner')return {generateMealPlan:(...args)=>{generated++;return require('../services/meals/planner.ts').generateMealPlan(...args);}};
  if(request==='@/services/meals/basket')return {basketFromMealPlan:(plan,p)=>({...generateBasket(p,catalog),engineVersion:'2',mealPlan:plan})};
  if(request==='@/components/BasketResult')return {BasketResult:props=>React.createElement('Result',props)};
  if(request==='@/context/PreferencesContext')return {usePreferences:()=>preferenceState};
  if(request==='@/hooks/useBasketFlow')return {useBasketFlow:()=>({edit:()=>{},disabled:false})};
  if(request==='@/lib/supabase')return {getSupabaseClient:()=>({})};
  if(request==='@/lib/theme')return {colors:{},ui:{}};
  if(request==='@/services/basket/catalog')return {loadBasketCatalog:(...args)=>load(...args)};
  if(request==='@/services/basket/basketGenerator')return {generateBasket:(...args)=>{generated++;return generateBasket(...args);}};
  if(request==='@/services/baskets')return {basketOwner:async()=>prefs().userId,basketPersistence:()=>({list:async()=>({baskets:[saved],warning:null}),save:async b=>{saveCalls++;await new Promise(resolve=>{resolveSave=resolve;});return {basket:{...b,syncStatus:'synced',cloudId:'id'},warning:null};}})};
  if(request.startsWith('@/'))request=path.resolve(path.dirname(require.resolve('../package.json')),request.slice(2));
  return originalLoad.call(this,request,parent,isMain);
};
for(const extension of ['.ts','.tsx'])require.extensions[extension]=(module,filename)=>{
  const result=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}});
  module._compile(result.outputText,filename);
};
const Screen=require('../app/basket-setup.tsx').default;
const flush=()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,15));});
test('actual screen requires meal confirmation, saves once on double tap, reopens a snapshot and aborts abandoned generation',async()=>{
  let renderer;
  await act(()=>{renderer=create(React.createElement(Screen));});await flush();
  assert.equal(generated,1);assert.equal(renderer.root.findAllByType('Result').length,0);
  assert.equal(renderer.root.findAllByType('MealReview').length,1);
  await act(()=>renderer.root.findByType('MealReview').props.onConfirm());
  assert.equal(renderer.root.findAllByType('Result').length,1);
  assert.equal(renderer.root.findByType('Screen').props.bottom,true);assert.equal(renderer.root.findByType('Screen').props.top,false);
  const saveButton=renderer.root.findAllByType('PrimaryButton').find(b=>b.props.label==='Save meal plan & basket');
  await act(async()=>{saveButton.props.onPress();saveButton.props.onPress();await Promise.resolve();});
  assert.equal(saveCalls,1);
  await act(async()=>{resolveSave();await Promise.resolve();});await flush();
  assert.ok(renderer.root.findAllByType('PrimaryButton').some(b=>b.props.label==='Basket saved'&&b.props.disabled));
  params={savedId:saved.id};await act(()=>renderer.update(React.createElement(Screen)));await flush();
  assert.equal(generated,1);assert.deepEqual(renderer.root.findByType('Result').props.result,saved.result);
  await act(()=>renderer.unmount());
  params={};let resolveLoad;let signal;
  load=async(_client,s)=>{signal=s;return new Promise(resolve=>{resolveLoad=resolve;});};
  await act(()=>{renderer=create(React.createElement(Screen));});await flush();
  await act(()=>renderer.unmount());assert.equal(signal.aborted,true);
  await act(async()=>{resolveLoad(catalog);await Promise.resolve();});await flush();assert.equal(generated,1);
});
