require('./register.cjs');
const { test } = require('node:test'), assert = require('node:assert/strict');
const React = require('react'), { create, act } = require('react-test-renderer');
const fs = require('node:fs'), path = require('node:path'), Module = require('node:module'), ts = require('typescript');
const { WeekPlanStore } = require('../services/week-plan-store.ts');
const { suggestMeals } = require('../services/meals/planner.ts');
const { prefs } = require('./basket-fixtures.cjs');
const { fullCatalog } = require('./meal-fixtures.cjs');
global.IS_REACT_ACT_ENVIRONMENT = true;
const date = '2026-10-05';
const people = ['adult', 'child'].map((id, index) => ({ id, name: id, kind: id, age: null, sex: null, dailyCalories: index ? 1400 : 2200, proteinTarget: 100, dietaryPreferences: ['none'], allergens: [], intolerances: [], isCurrentUser: !index }));
const preferences = prefs({ householdSize: 2, participants: people });
let store;
const stub = name => { function Stub(props) { return React.createElement(name, props, props.children); } return Stub; };
const original = Module._load;
Module._load = function(request, parent, isMain) {
  if (request === 'react-native') return { Text: 'Text', View: 'View' };
  if (request === 'expo-router') return { router: { push() {}, replace() {} }, useLocalSearchParams: () => ({ date }) };
  if (request === '@/components/ui') return Object.fromEntries(['ErrorMessage','PrimaryButton','Screen','ScreenHeader','SecondaryButton','SectionCard','SelectionChip','TextButton'].map(n => [n, stub(n)]));
  if (request === '@/context/PreferencesContext') return { usePreferences: () => ({ saved: preferences }) };
  if (request === '@/context/WeekPlanContext') return { useWeekPlan: () => ({ ...React.useSyncExternalStore(store.subscribe, store.getSnapshot), store }) };
  if (request === '@/components/MealImage') return { MealImage: stub('MealImage') };
  if (request === '@/lib/theme') return { ui: {} };
  if (request.startsWith('@/')) request = path.resolve(path.dirname(require.resolve('../package.json')), request.slice(2));
  return original.call(this, request, parent, isMain);
};
require.extensions['.tsx'] = (module, file) => module._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX } }).outputText, file);
const Day = require('../app/plan/[date].tsx').default;
Module._load = original;

test('presence remains editable after removing a child and separate dishes protect each others participants', async () => {
  store = new WeekPlanStore({ getItem: async () => null, setItem: async () => {} }, 'ui');
  await store.initialize(); store.open(date, preferences); store.toggleDay(date, preferences);
  store.choose(date, 'dinner', suggestMeals(store.getSnapshot().plan, date, 'dinner', preferences, fullCatalog)[0], preferences);
  let screen; await act(() => { screen = create(React.createElement(Day)); });
  const chips = () => screen.root.findAllByType('SelectionChip').filter(n => ['adult', 'child (child)'].includes(n.props.label));
  const full = store.getSnapshot().plan.items[0].servings;
  await act(() => chips().find(n => n.props.label === 'child (child)').props.onPress());
  assert.equal(chips().length, 2, 'both presence controls stay visible');
  assert.equal(chips().find(n => n.props.label === 'child (child)').props.selected, false);
  await act(() => chips().find(n => n.props.label === 'child (child)').props.onPress());
  assert.ok(Math.abs(store.getSnapshot().plan.items[0].servings - full) < 1e-9);
  await act(() => store.choose(date, 'dinner', suggestMeals(store.getSnapshot().plan, date, 'dinner', preferences, fullCatalog, [], ['child'])[0], preferences, ['child']));
  assert.equal(chips().length, 4);
  assert.equal(chips().filter(n => n.props.disabled).length, 2, 'people already assigned to another dish cannot be duplicated');
  await act(() => screen.root.findAllByType('TextButton').filter(n => n.props.label === 'Not at home')[1].props.onPress());
  assert.equal(store.getSnapshot().plan.items.length, 1, 'only the selected dish is removed');
  assert.equal(chips().find(n => n.props.label === 'child (child)').props.disabled, false);
  await act(() => chips().find(n => n.props.label === 'child (child)').props.onPress());
  assert.equal(store.getSnapshot().plan.items[0].participantIds, undefined);
  await act(() => screen.unmount());
});
