const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module');
const ts=require('typescript'),React=require('react'),{create,act}=require('react-test-renderer');
require('./register.cjs');
const {prefs}=require('./basket-fixtures.cjs');const {generateMealPlan}=require('../services/meals/planner.ts');
global.IS_REACT_ACT_ENVIRONMENT=true;
const original=Module._load;
Module._load=function(request,parent,isMain){
 if(request==='react-native')return {Text:'Text',View:'View',Image:'Image'};
 if(request==='./ui'&&parent.filename.endsWith('MealPlanReview.tsx'))return Object.fromEntries(['PrimaryButton','SecondaryButton','SectionCard'].map(n=>[n,p=>React.createElement(n,p,p.children)]));
 if(request==='../lib/theme')return {ui:{}};
 return original.call(this,request,parent,isMain);
};
require.extensions['.tsx']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);
const {MealPlanReview}=require('../components/MealPlanReview.tsx');
const {MealImage}=require('../components/MealImage.tsx');
const {meals}=require('../data/meals.ts');
test('failed meal image collapses without removing meal text or breaking another image',async()=>{
 let renderer;const oats=meals.find(m=>m.id==='oat-berries'),salmon=meals.find(m=>m.id==='salmon-rice');
 await act(()=>{renderer=create(React.createElement(MealImage,{meal:oats}));});
 await act(()=>renderer.root.findByType('Image').props.onError());
 assert.equal(renderer.toJSON(),null);
 await act(()=>renderer.update(React.createElement(MealImage,{meal:salmon})));
 assert.equal(renderer.root.findByType('Image').props.accessibilityLabel,salmon.name);
 await act(()=>renderer.unmount());
});
test('meal review displays twelve slots, changes a compatible meal and explicitly confirms',async()=>{
 const p=prefs({planningDays:3,dietaryPreferences:['vegan']});let plan=generateMealPlan(p),confirmed=0,renderer;
 const render=()=>React.createElement(MealPlanReview,{plan,preferences:p,onChange:next=>{plan=next;renderer.update(render());},onConfirm:()=>confirmed++});
 await act(()=>{renderer=create(render());});assert.equal(confirmed,0);assert.equal(renderer.root.findAllByType('SectionCard').length,13);
 const before=plan.items[0].meal.id;await act(()=>renderer.root.findAllByType('SecondaryButton').find(b=>b.props.label==='Replace meal').props.onPress());
 await act(()=>renderer.root.findAllByType('SecondaryButton').find(b=>b.props.label==='I want to cook').props.onPress());
 const alternative=renderer.root.findAllByType('SecondaryButton').find(b=>b.props.label.includes('kcal'));assert.ok(alternative);
 await act(()=>alternative.props.onPress());assert.notEqual(plan.items[0].meal.id,before);assert.ok(plan.items[0].meal.dietaryTags.includes('vegan'));
 await act(()=>renderer.root.findByType('PrimaryButton').props.onPress());assert.equal(confirmed,1);await act(()=>renderer.unmount());
});
test('replacement UI separates modes, supports back, and commits only category or eating-out selection',async()=>{
 const p=prefs({planningDays:3});let plan=generateMealPlan(p),renderer;
 const render=()=>React.createElement(MealPlanReview,{plan,preferences:p,onChange:next=>{plan=next;renderer.update(render());},onConfirm:()=>{}});
 await act(()=>{renderer=create(render());});
 const buttons=()=>renderer.root.findAllByType('SecondaryButton');
 const click=label=>act(()=>buttons().find(b=>b.props.label===label).props.onPress());
 const openLunch=()=>act(()=>buttons().filter(b=>b.props.label==='Replace meal')[1].props.onPress());
 await openLunch();assert.ok(!buttons().some(b=>b.props.label.includes('kcal')));
 for(const name of ['I want to cook','I don’t want to cook','I only want to heat it up','I’m eating out'])assert.ok(buttons().some(b=>b.props.label===name));
 await click('I don’t want to cook');assert.ok(buttons().some(b=>b.props.label==='Salad'));assert.ok(buttons().some(b=>b.props.label==='Pizza'));
 await click('Back to meal options');await click('I only want to heat it up');assert.ok(!buttons().some(b=>b.props.label==='Salad'));
 await click('Lasagne');assert.equal(plan.items[1].mealMode,'heat_and_eat');assert.equal(plan.items[1].readyMealCategory,'lasagne');assert.equal(plan.items[1].readyMealMatch,undefined);
 await openLunch();await click('I’m eating out');assert.equal(plan.items[1].mealMode,'eat_out');assert.equal(plan.items[1].readyMealCategory,undefined);
 await openLunch();await click('I want to cook');assert.ok(buttons().some(b=>b.props.label.includes('kcal')));
 await act(()=>buttons().find(b=>b.props.label.includes('kcal')).props.onPress());assert.equal(plan.items[1].mealMode,'cook');
 await act(()=>renderer.unmount());
});
